In [2]:
import os
import pathlib

import pandas as pd
import numpy as np

import tensorflow as tf
from tensorflow import keras

In [4]:
np.set_printoptions(precision=4)

In [5]:
dataset = tf.data.Dataset.from_tensor_slices([8, 3, 0, 8, 2, 1])
dataset

2023-02-09 13:41:01.948713: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2023-02-09 13:41:01.948780: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2023-02-09 13:41:01.948835: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (mike-HP-EliteBook-Folio-9470m): /proc/driver/nvidia/version does not exist


<TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.int32, name=None)>

In [7]:
for i in dataset:
    print(i.numpy())

8
3
0
8
2
1


In [8]:
it = iter(dataset)

In [10]:
it.next().numpy()

3

In [11]:
it.next().numpy()

0

In [12]:
# add all the elements in the dataset
dataset.reduce(0, lambda state, value: state+value).numpy()

22

In [22]:
tf.random.set_seed(0)
dataset1 = tf.data.Dataset.from_tensor_slices(tf.random.uniform([4, 10]))
for i in dataset1:
    print(i.numpy())

[0.292  0.2066 0.5354 0.5613 0.4167 0.8078 0.4932 0.9981 0.6967 0.1254]
[0.7098 0.6624 0.5723 0.3648 0.4205 0.6301 0.9138 0.6616 0.8335 0.084 ]
[0.2798 0.0155 0.7264 0.7655 0.6799 0.5327 0.7565 0.0474 0.0504 0.7517]
[0.1727 0.3119 0.2914 0.1005 0.1657 0.7697 0.5857 0.982  0.9148 0.1417]


In [23]:
dataset2 = tf.data.Dataset.from_tensor_slices(
   (tf.random.uniform([4]),
    tf.random.uniform([4, 100], maxval=100, dtype=tf.int32)))

dataset2.element_spec

(TensorSpec(shape=(), dtype=tf.float32, name=None),
 TensorSpec(shape=(100,), dtype=tf.int32, name=None))

In [26]:
dataset4 = tf.data.Dataset.from_tensors(tf.SparseTensor(indices=[[0, 0], [1, 2]], values=[1, 2], dense_shape=[3, 4]))
dataset4.element_spec

SparseTensorSpec(TensorShape([3, 4]), tf.int32)

In [30]:
for i in dataset4:
    print(i)

SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))


In [31]:
dataset4.element_spec.value_type

tensorflow.python.framework.sparse_tensor.SparseTensor

In [33]:
dataset1.element_spec.value_type

tensorflow.python.framework.ops.Tensor

In [34]:
dataset2.element_spec

(TensorSpec(shape=(), dtype=tf.float32, name=None),
 TensorSpec(shape=(100,), dtype=tf.int32, name=None))

In [35]:
dataset2 = tf.data.Dataset.from_tensor_slices(
   (tf.random.uniform([4]),
    tf.random.uniform([4, 100], maxval=100, dtype=tf.int32)))

dataset2

<TensorSliceDataset element_spec=(TensorSpec(shape=(), dtype=tf.float32, name=None), TensorSpec(shape=(100,), dtype=tf.int32, name=None))>

In [38]:
dataset3 = tf.data.Dataset.zip((dataset1, dataset2))

for elem in dataset3:
    print(elem)

(<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([0.292 , 0.2066, 0.5354, 0.5613, 0.4167, 0.8078, 0.4932, 0.9981,
       0.6967, 0.1254], dtype=float32)>, (<tf.Tensor: shape=(), dtype=float32, numpy=0.17513537>, <tf.Tensor: shape=(100,), dtype=int32, numpy=
array([28, 65, 18,  2, 57, 35, 47, 84, 33, 89, 89, 92, 26, 86, 36,  1, 30,
       66, 23, 10, 53, 43, 90, 38, 30, 74, 25, 97, 37, 45, 97, 48, 64, 24,
       26, 41, 17, 46,  2, 34, 44, 16, 90, 71, 43, 94, 68, 88, 10, 17, 10,
        2, 20, 63, 67, 68, 11, 61, 53, 18, 56, 57, 13, 11, 98, 24, 25, 95,
       31, 21, 29, 37, 15, 98, 14, 69, 18, 97, 50, 63, 34, 35, 30, 82, 15,
       50, 94, 85, 96,  5, 49, 52, 30, 39, 32, 65, 25, 56, 77, 41],
      dtype=int32)>))
(<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([0.7098, 0.6624, 0.5723, 0.3648, 0.4205, 0.6301, 0.9138, 0.6616,
       0.8335, 0.084 ], dtype=float32)>, (<tf.Tensor: shape=(), dtype=float32, numpy=0.3179742>, <tf.Tensor: shape=(100,), dtype=int32, numpy=
array([33,

In [40]:
dataset2.element_spec

(TensorSpec(shape=(), dtype=tf.float32, name=None),
 TensorSpec(shape=(100,), dtype=tf.int32, name=None))

In [42]:
for a,(b,c) in dataset3:
    print(a,b,c)

tf.Tensor([0.292  0.2066 0.5354 0.5613 0.4167 0.8078 0.4932 0.9981 0.6967 0.1254], shape=(10,), dtype=float32) tf.Tensor(0.17513537, shape=(), dtype=float32) tf.Tensor(
[28 65 18  2 57 35 47 84 33 89 89 92 26 86 36  1 30 66 23 10 53 43 90 38
 30 74 25 97 37 45 97 48 64 24 26 41 17 46  2 34 44 16 90 71 43 94 68 88
 10 17 10  2 20 63 67 68 11 61 53 18 56 57 13 11 98 24 25 95 31 21 29 37
 15 98 14 69 18 97 50 63 34 35 30 82 15 50 94 85 96  5 49 52 30 39 32 65
 25 56 77 41], shape=(100,), dtype=int32)
tf.Tensor([0.7098 0.6624 0.5723 0.3648 0.4205 0.6301 0.9138 0.6616 0.8335 0.084 ], shape=(10,), dtype=float32) tf.Tensor(0.3179742, shape=(), dtype=float32) tf.Tensor(
[33 70 45 55 80 20 34 57 48 17 85 98 52  8 52 47 22 97 84  1 52 43 33 12
 60 65 61 72 83 57 95 24 63 44 76 51 19 53 25 58 42 69 29 65 39 78 85 14
 69  5 10  2 31 65 58  7 63 19 37 49 75 98  5 22 12 45 99 88 30 53 20 15
 27 95 23 38 26 24 22 78 70 45 45  7 22 82 39  1 28 72 72 10 37 78 40 95
  5  0 32 24], shape=(100,), dtype=in

In [43]:
train, test = tf.keras.datasets.fashion_mnist.load_data()

In [45]:
images, labels = train

In [48]:
images.shape

(60000, 28, 28)

In [51]:
images.max(), images.min()

(255, 0)

In [54]:
type(train)

tuple

In [56]:
images = images/255.0
images.max(), images.min()

(0.00392156862745098, 0.0)

In [58]:
dataset = tf.data.Dataset.from_tensor_slices((images, labels))

2023-02-09 14:00:01.284511: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 376320000 exceeds 10% of free system memory.


In [60]:
dataset.element_spec

(TensorSpec(shape=(28, 28), dtype=tf.float64, name=None),
 TensorSpec(shape=(), dtype=tf.uint8, name=None))

In [61]:
def count(stop):
    i=0
    while i<stop:
        yield i
        i+=1

In [65]:
for n in count(5):
    print(n)

0
1
2
3
4


In [67]:
type(count(5))

generator

In [75]:
# ds_counter = tf.data.Dataset.from_generator(count, args=[25], output_types=tf.int32, output_shapes = (5,5), ) # testing the shape paramete
ds_counter = tf.data.Dataset.from_generator(count, args=[25], output_types=tf.int32, output_shapes = (), )

In [76]:
ds_counter.element_spec.value_type

tensorflow.python.framework.ops.Tensor

In [77]:
for count_batch in ds_counter.repeat().batch(10).take(10):
  print(count_batch.numpy())

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]
[20 21 22 23 24  0  1  2  3  4]
[ 5  6  7  8  9 10 11 12 13 14]
[15 16 17 18 19 20 21 22 23 24]
[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]
[20 21 22 23 24  0  1  2  3  4]
[ 5  6  7  8  9 10 11 12 13 14]
[15 16 17 18 19 20 21 22 23 24]


In [78]:
def gen_series():
  i = 0
  while True:
    size = np.random.randint(0, 10)
    yield i, np.random.normal(size=(size,))
    i += 1

In [79]:
for i, series in gen_series():
  print(i, ":", str(series))
  if i > 5:
    break

0 : [-0.6346  0.9886  1.1412]
1 : [-0.1763 -0.8237 -0.2334]
2 : [ 1.409  -1.7412  0.3004 -1.9827  1.0813 -0.9573  0.6176  1.0134]
3 : [ 0.3309  0.788  -0.8567  0.3214 -0.181 ]
4 : []
5 : [-0.6726  1.729  -1.5526 -0.4692  2.0061 -0.7966  0.0509  1.4406 -0.6729]
6 : [ 4.9721e-01  7.9137e-04  5.8198e-02  2.2091e+00  5.6276e-01 -1.1325e+00
  6.6120e-01 -4.8522e-02  4.8753e-01]


In [86]:
for elem in dataset1.repeat(10).batch(10).take(10):
    print(elem.numpy())

[[0.292  0.2066 0.5354 0.5613 0.4167 0.8078 0.4932 0.9981 0.6967 0.1254]
 [0.7098 0.6624 0.5723 0.3648 0.4205 0.6301 0.9138 0.6616 0.8335 0.084 ]
 [0.2798 0.0155 0.7264 0.7655 0.6799 0.5327 0.7565 0.0474 0.0504 0.7517]
 [0.1727 0.3119 0.2914 0.1005 0.1657 0.7697 0.5857 0.982  0.9148 0.1417]
 [0.292  0.2066 0.5354 0.5613 0.4167 0.8078 0.4932 0.9981 0.6967 0.1254]
 [0.7098 0.6624 0.5723 0.3648 0.4205 0.6301 0.9138 0.6616 0.8335 0.084 ]
 [0.2798 0.0155 0.7264 0.7655 0.6799 0.5327 0.7565 0.0474 0.0504 0.7517]
 [0.1727 0.3119 0.2914 0.1005 0.1657 0.7697 0.5857 0.982  0.9148 0.1417]
 [0.292  0.2066 0.5354 0.5613 0.4167 0.8078 0.4932 0.9981 0.6967 0.1254]
 [0.7098 0.6624 0.5723 0.3648 0.4205 0.6301 0.9138 0.6616 0.8335 0.084 ]]
[[0.2798 0.0155 0.7264 0.7655 0.6799 0.5327 0.7565 0.0474 0.0504 0.7517]
 [0.1727 0.3119 0.2914 0.1005 0.1657 0.7697 0.5857 0.982  0.9148 0.1417]
 [0.292  0.2066 0.5354 0.5613 0.4167 0.8078 0.4932 0.9981 0.6967 0.1254]
 [0.7098 0.6624 0.5723 0.3648 0.4205 0.6301 0.9138

In [88]:
ds_series = tf.data.Dataset.from_generator(
    gen_series, 
    output_types=(tf.int32, tf.float32), 
    output_shapes=((), (None,)))

ds_series

<FlatMapDataset element_spec=(TensorSpec(shape=(), dtype=tf.int32, name=None), TensorSpec(shape=(None,), dtype=tf.float32, name=None))>

In [92]:
# for i,j in ds_series:
#     print(i.numpy(),j.numpy())
#     break

In [93]:
ds_series_batch = ds_series.shuffle(20).padded_batch(10)
ids, sequence_batch = next(iter(ds_series_batch))
print(ids.numpy())
print()
print(sequence_batch.numpy())

[17  9 14 15  1 12  0 10 18 11]

[[ 8.2476e-02  1.0103e+00 -1.2161e-01  7.6258e-01  1.9050e-01  3.2723e-01
   6.6298e-01  1.4014e+00  1.0289e+00]
 [ 5.2077e-01 -2.3660e-01  5.6734e-01  5.5744e-01 -2.2658e-01  0.0000e+00
   0.0000e+00  0.0000e+00  0.0000e+00]
 [-1.1573e+00  1.0806e+00 -1.1895e+00  5.0640e-01 -4.8898e-01  3.9813e-01
   4.6938e-01  0.0000e+00  0.0000e+00]
 [-3.1646e-01  8.5929e-01 -2.1756e-02  1.6715e-01 -5.1770e-01 -1.8004e+00
  -2.4158e-01 -1.2045e+00  0.0000e+00]
 [ 1.0936e+00  1.1063e+00  7.6926e-01  6.1839e-02 -1.5312e+00 -1.7193e+00
   0.0000e+00  0.0000e+00  0.0000e+00]
 [ 3.9760e-01  5.5510e-01  1.4184e-01  0.0000e+00  0.0000e+00  0.0000e+00
   0.0000e+00  0.0000e+00  0.0000e+00]
 [-5.4871e-01  2.6501e+00 -2.5763e-03  0.0000e+00  0.0000e+00  0.0000e+00
   0.0000e+00  0.0000e+00  0.0000e+00]
 [-1.2966e+00  1.3072e-01 -1.1018e+00  0.0000e+00  0.0000e+00  0.0000e+00
   0.0000e+00  0.0000e+00  0.0000e+00]
 [-3.4758e-01  0.0000e+00  0.0000e+00  0.0000e+00  0.0000e+00  

In [95]:
# flowers = tf.keras.utils.get_file(
#     'dataset',
#     '/home/mike/Downloads/archive(32).zip',
#     untar=True)

In [96]:
img_gen = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255, rotation_range=20)

In [103]:
images, labels = next(img_gen.flow_from_directory("/home/mike/Downloads/archive(32)/dataset/train"))

Found 6552 images belonging to 102 classes.


In [115]:
# names = pd.read_json("/home/mike/Downloads/archive(32)/cat_to_name.json")

In [105]:
images.shape, labels.shape

((32, 256, 256, 3), (32, 102))

In [106]:
labels[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
      dtype=float32)

In [107]:
print(images.dtype, images.shape)
print(labels.dtype, labels.shape)

float32 (32, 256, 256, 3)
float32 (32, 102)


In [112]:
ds = tf.data.Dataset.from_generator(
    lambda: img_gen.flow_from_directory("/home/mike/Downloads/archive(32)/dataset/train"), 
    output_types=(tf.float32, tf.float32), 
    output_shapes=([32,256,256,3], [32,102])
)

ds.element_spec

(TensorSpec(shape=(32, 256, 256, 3), dtype=tf.float32, name=None),
 TensorSpec(shape=(32, 102), dtype=tf.float32, name=None))

In [113]:
for images, labels in ds.take(1):
  print('images.shape: ', images.shape)
  print('labels.shape: ', labels.shape)


Found 6552 images belonging to 102 classes.
images.shape:  (32, 256, 256, 3)
labels.shape:  (32, 102)


2023-02-09 14:29:35.178314: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 25165824 exceeds 10% of free system memory.


In [116]:
dataset = tf.data.TextLineDataset("/home/mike/Downloads/archive(37) (1)/data/texts")

In [121]:
dataset.element_spec.value_type

tensorflow.python.framework.ops.Tensor

In [123]:
type(dataset)

tensorflow.python.data.ops.readers.TextLineDatasetV2

In [127]:
# for line in dataset.take(5):
#   print(line.numpy())

In [129]:
# files_ds = tf.data.Dataset.from_tensor_slices("/home/mike/Downloads/archive(32)/dataset/train")
# lines_ds = files_ds.interleave(tf.data.TextLineDataset, cycle_length=3)

In [130]:
emails = tf.data.TextLineDataset("/home/mike/Downloads/spam detection/SPAM text message 20170820 - Data.csv")

In [132]:
for line in emails.take(10):
    print(line.numpy())

b'Category,Message'
b'ham,"Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat..."'
b'ham,Ok lar... Joking wif u oni...'
b"spam,Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's"
b'ham,U dun say so early hor... U c already then say...'
b'ham,"Nah I don\'t think he goes to usf, he lives around here though"'
b'spam,"FreeMsg Hey there darling it\'s been 3 week\'s now and no word back! I\'d like some fun you up for it still? Tb ok! XxX std chgs to send, \xc2\xa31.50 to rcv"'
b'ham,Even my brother is not like to speak with me. They treat me like aids patent.'
b"ham,As per your request 'Melle Melle (Oru Minnaminunginte Nurungu Vettam)' has been set as your callertune for all Callers. Press *9 to copy your friends Callertune"
b'spam,WINNER!! As a valued network customer you have been selected to receivea \xc2\xa3900 prize reward! To